data:
  train_batch_size: 256
  val_batch_size: 8
  micro_batch_size: null # will be deprecated, use micro_batch_size_per_gpu
  micro_batch_size_per_gpu: 4  # this is also val batch size
  train_files: ~/data/gsm8k/train.parquet
  val_files: ~/data/gsm8k/test.parquet
  # Single-turn settings
  prompt_key: question
  response_key: answer
  prompt_dict_keys: ['question']
  response_dict_keys: ['answer']
  # Multi-turn settings
  multiturn:
    enable: false  # Set to true to use multi-turn dataset
    messages_key: messages  # Key for messages list in multi-turn mode
  max_length: 1024
  truncation: error
  balance_dp_token: False
  chat_template: null
  custom_cls:
    path: null
    name: null
  shuffle: False
model:
  path: ~/models/gemma-1.1-7b-it
  override_config:
    model_config: {}
    moe_config:
      freeze_moe_router: False
  external_lib: null
  enable_gradient_checkpointing: False
  trust_remote_code: False
  lora_rank: 0  # Set to positive value to enable LoRA (e.g., 32)
  lora_alpha: 16  # LoRA scaling factor
  target_modules: all-linear  # Target modules for LoRA adaptation
  use_liger: False
optim:
  lr: 1e-5
  betas: [0.9, 0.95]
  weight_decay: 0.01
  warmup_steps_ratio: 0.1
  clip_grad: 1.0
  lr_scheduler: cosine
megatron:
  param_offload: False
  grad_offload: False
  optimizer_offload: False
  tensor_model_parallel_size: 1
  expert_model_parallel_size: 1
  expert_tensor_parallel_size: null
  pipeline_model_parallel_size: 1
  virtual_pipeline_model_parallel_size: null # change VPP interface for parallelism tests
  context_parallel_size: 1
  sequence_parallel: True
  use_distributed_optimizer: True
  use_dist_checkpointing: False
  dist_checkpointing_path: null
  seed: 42
  override_transformer_config: {} # additional transformer config like: num_layers_in_first(/last)_pipeline_stage
ulysses_sequence_parallel_size: 1
data_loader_seed: null
use_remove_padding: False
checkpoint:
  contents: ['model', 'optimizer', 'extra']  # with 'hf_model' you can save whole model as hf format, now only use sharded model checkpoint to save space
trainer:
  default_local_dir: /tmp/sft_model
  default_hdfs_dir: hdfs://tmp/experiments/gsm8k/gemma-1.1-7b-it/ # change the hdfs path here
  resume_path: null
  project_name: megatron-sft
  experiment_name: test
  total_epochs: 4
  total_training_steps: null
  logger: ['console']
  seed: 1
  nnodes: 1
  n_gpus_per_node: 8
  ray_wait_register_center_timeout: 300
  device: cuda
ray_init:
  num_cpus: null # `None` means using all CPUs
profile: # profile the actor model in `update_policy` 
  use_profile: False # open it when you want to profile the actor model
  profile_ranks: null # list, you can specify the ranks to profile
  step_start: -1 # start step in update_policy 
  step_end: -1 # end step 
  save_path: null # the path to save the profile result